[package]
name = "rust-alpine-missing-musl-dev"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"futures-macro" = "0.3.15"